#!/bin/bash

data_fs=ext4
data_label=data
data_mount=/data

function lookup_disk_device_from_root {
    root_device=/dev/root
    if [ -L "${root_device}" ];then
        root_device=/dev/$(basename "$(readlink "${root_device}")")
    fi
    lsblk -p -n -r -s -o NAME,TYPE "${root_device}" |\
        grep disk | cut -f1 -d ' '
}

function _partition_count {
    if [ -z "$1" ]; then
        echo 0
    else
        lsblk "$1" -p -r -n -o TYPE | grep -c part
    fi
}

root_disk=$(lookup_disk_device_from_root)

partitions_origin=$(_partition_count "${root_disk})")

echo -e "n\n\n\n\n\nw\ny\n" | gdisk "${root_disk}"

if partprobe "${root_disk}";then
    if [ "$(_partition_count "${root_disk}")" -gt "${partitions_origin}" ];then
        data_partition=$(lsblk "${root_disk}" -p -r -n -o NAME | tail -n1)
        if mkfs."${data_fs}" -L "${data_label}" "${data_partition}"; then
            mkdir -p ${data_mount}
            echo "LABEL=${data_label} ${data_mount} ${data_fs} defaults 0 0" \
                >>/etc/fstab
        fi
    fi
fi

mount -L ${data_label} ${data_mount}

# NOTES:
# - consider self destruction of this code, to avoid recall
# - consider backup/move of data if data_mount has data before data part
# - consider quota setup of data
